title: jekyll-forestry-snipcart
email: jvaage@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is an eCommerce solution for Jekyll. It has support for Forestry.io and SnipCart.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# See /forestry/settings.yml
# Collections defined here and used by Jekyll, are defined as sections in settings.yml.
# Also, note the .forestry/front_matter/templates which correspond to any collection/section you use.

collections:
  products:
    output: true
    permalink: "/products/:path/"
  event-tiers:
    output: true
    permalink: "/eventtiers/:path/"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
