---
label: Product
hide_body: false
fields:
- name: product_type
  type: select
  default: Single
  config:
    required: false
    options:
    - Single
    - T-Shirt
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Product Type
- name: t-shirt_small_stock_count
  type: number
  label: T-Shirt Small Stock Count
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
  showOnly:
    field: product_type
    value: T-Shirt
- name: t-shirt_medium_stock_count
  type: number
  label: T-Shirt Medium Stock Count
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
  showOnly:
    field: product_type
    value: T-Shirt
- name: t-shirt_large_stock_count
  type: number
  label: T-Shirt Large Stock Count
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
  showOnly:
    field: product_type
    value: T-Shirt
- name: size
  type: select
  default: []
  config:
    required: false
    options:
    - Small
    - Medium
    - Large
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Size
  showOnly:
    field: product_type
    value: Single
- name: in_stock
  type: boolean
  label: In Stock
  default: false
  showOnly:
    field: product_type
    value: Single
- name: stock_count
  type: number
  label: Stock Count
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
  showOnly:
    field: product_type
    value: Single
- name: title
  type: text
  config:
    required: false
  label: Title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: price
  type: number
  label: Price
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: sale_price
  type: text
  config:
    required: false
  label: Sale Price
- name: featured_image
  type: file
  config:
    maxSize: 250
  label: Featured Image
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: layout
  type: text
  config:
    required: false
  hidden: true
  label: Layout
  default: product
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
pages:
- _products/beginner-s-orb.md
- _products/bitter-solitude.md
- _products/fashion-sense.md
- _products/forever-reckless-t-shirt.md
- _products/nice-horse.md
- _products/swimming-lessons.md
